use std::path::Path;

// The embedded frontend manifest (struct `EmbeddedAsset` + `EMBEDDED_WEB`),
// generated by build.rs from `CC_SWITCH_WEB_DIST`. `EMBEDDED_WEB` is empty when
// that env var was unset at build time (then the server serves `--assets`).
include!(concat!(env!("OUT_DIR"), "/web_embed.rs"));

/// The cc-switch app icon, vendored from the desktop project's Tauri icons,
/// served as the web dashboard's favicon so the browser tab matches cc-switch.
pub(crate) const FAVICON_PNG: &[u8] = include_bytes!("favicon.png");

/// Chrome injected into `<head>`: a frameless, modern-macOS window look (rounded
/// corners + soft shadow, NO titlebar bar and NO border) with the traffic-light
/// dots floating over the top-left of the content, plus the cc-switch favicon.
///
/// The window IS the `<body>` element (the desktop backdrop lives on `<html>`),
/// so it contains not just `#root` but every body-level React portal — provider
/// dialogs, dropdowns, toasts — keeping them inside the frame too. `contain`
/// makes `<body>` the containing block for those `position:fixed` elements (so
/// they anchor to the window, not the viewport) AND clips them to the rounded
/// corners, while leaving the window's own drop shadow intact.
///
/// A tiny script seeds the theme class before paint (no FOUC). The chrome keys
/// its CSS off the same `html.light` / `html.dark` classes the app's own
/// `ThemeProvider` toggles, so the frame always matches the app's theme.
const CHROME_HEAD: &str = r##"<link rel="icon" type="image/png" href="/favicon.png">
<style data-ccx-chrome>
:root{
  --ccx-desk:linear-gradient(135deg,#d7e1ee,#c8d6e6 50%,#d4dfec);
  --ccx-win:#ffffff;
  --ccx-shadow:0 24px 70px -24px rgba(15,23,42,.40),0 8px 24px -12px rgba(15,23,42,.20);
}
html.dark{
  --ccx-desk:radial-gradient(1100px 560px at 82% -12%,rgba(34,197,94,.10),transparent 60%),linear-gradient(135deg,#04060b,#080c14 55%,#0b0f18);
  --ccx-win:#0f172a;
  --ccx-shadow:0 30px 90px -24px rgba(0,0,0,.80),0 8px 24px -12px rgba(0,0,0,.60);
}
html{box-sizing:border-box;height:100%;margin:0;padding:10vh 24px;background:var(--ccx-desk);}
body{position:relative;margin:0 auto;height:100%;width:100%;max-width:1440px;display:flex;flex-direction:column;border-radius:14px;overflow:hidden;contain:layout paint;background:var(--ccx-win);box-shadow:var(--ccx-shadow);}
#root{flex:1;min-height:0;}
#root .h-screen{height:100%!important;}
#root .min-h-screen{min-height:100%!important;}
/* Traffic-light dots float over the app's top drag-strip (28px on macOS) so
   they read as a unified titlebar without a separate chrome bar. Decorative. */
.ccx-lights{position:absolute;top:16px;left:21px;z-index:9999;display:flex;gap:8px;pointer-events:none;}
.ccx-light{width:12px;height:12px;border-radius:50%;box-shadow:inset 0 0 0 .5px rgba(0,0,0,.22);}
.ccx-light.r{background:#ff5f57;}.ccx-light.y{background:#febc2e;}.ccx-light.g{background:#28c840;}
@media (max-width:680px){html{padding:0;}body{border-radius:0;box-shadow:none;max-width:none;}.ccx-lights{display:none;}}
</style>
<script data-ccx-chrome>
(function(){var K="cc-switch-theme";function r(v){if(v==="dark"||v==="light")return v;return(window.matchMedia&&matchMedia("(prefers-color-scheme: dark)").matches)?"dark":"light";}try{var t=r(localStorage.getItem(K)),e=document.documentElement;e.classList.remove("light","dark");e.classList.add(t);}catch(_){}})();
</script>"##;

/// Floating traffic-light dots, inserted as the first child of `<body>` so they
/// overlay the window's top-left corner.
const LIGHTS: &str = r##"<span class="ccx-lights" aria-hidden="true"><span class="ccx-light r"></span><span class="ccx-light y"></span><span class="ccx-light g"></span></span>"##;

/// Inject the macOS-window chrome into the SPA shell: add the chrome styles +
/// favicon + theme script before `</head>`, retitle the tab to match cc-switch,
/// and insert the floating dots as the first `<body>` child. The window itself
/// is `<body>` (styled by `CHROME_HEAD`), so no wrapper around `#root` is needed
/// and body-level portals stay framed too. Each replacement is single-shot; a
/// missing marker just skips that step so the app still boots.
pub fn inject_shell(html: &str) -> String {
    let mut out = if html.contains("</head>") {
        html.replacen("</head>", &format!("{CHROME_HEAD}</head>"), 1)
    } else {
        html.to_string()
    };
    out = out.replacen(
        "<title>cc-switch-web</title>",
        "<title>CC Switch</title>",
        1,
    );
    out.replacen("<body>", &format!("<body>{LIGHTS}"), 1)
}

/// Whether a frontend was embedded into the binary at build time.
pub fn embedded_present() -> bool {
    !EMBEDDED_WEB.is_empty()
}

/// Look up an embedded asset by request path (leading `/` optional).
pub fn embedded_asset(req_path: &str) -> Option<&'static EmbeddedAsset> {
    let want = req_path.trim_start_matches('/');
    EMBEDDED_WEB.iter().find(|a| a.path == want)
}

/// The embedded `index.html` with the macOS-window chrome injected, or `None`
/// if no frontend was embedded. `index.html` is embedded raw (not gzipped)
/// precisely so the chrome can be injected here at runtime.
pub fn embedded_index_html() -> Option<String> {
    let asset = embedded_asset("index.html")?;
    let html = std::str::from_utf8(asset.bytes).ok()?;
    Some(inject_shell(html))
}

/// Read the built `index.html` from `dir` and inject the window chrome. Returns
/// a minimal placeholder if the file can't be read so the server still responds.
pub fn load_injected_index(dir: &Path) -> String {
    match std::fs::read_to_string(dir.join("index.html")) {
        Ok(html) => inject_shell(&html),
        Err(err) => {
            log::warn!("web: failed to read index.html for chrome injection: {err}");
            "<!doctype html><html><head><meta charset=\"utf-8\"><title>CC Switch</title></head><body>index.html not found in --assets directory</body></html>".to_string()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inject_adds_chrome_dots_favicon_and_title() {
        let html = r#"<!DOCTYPE html><html><head><title>cc-switch-web</title></head><body><div id="root"></div></body></html>"#;
        let out = inject_shell(html);
        // chrome styles + favicon land before </head>
        assert!(out.contains("data-ccx-chrome"));
        assert!(out.contains(r#"<link rel="icon" type="image/png" href="/favicon.png">"#));
        assert!(out.find("data-ccx-chrome").unwrap() < out.find("</head>").unwrap());
        // tab retitled
        assert!(out.contains("<title>CC Switch</title>"));
        assert!(!out.contains("cc-switch-web"));
        // dots are the first body child; #root left untouched (still one)
        assert!(out.contains(&format!("<body>{LIGHTS}")));
        assert_eq!(out.matches(r#"id="root""#).count(), 1);
    }

    #[test]
    fn inject_is_noop_safe_without_markers() {
        let html = "<div>plain, no head or body markers</div>";
        let out = inject_shell(html);
        assert_eq!(out, html);
    }

    #[test]
    fn favicon_is_a_png() {
        assert_eq!(&FAVICON_PNG[1..4], b"PNG");
    }
}
